import * as PDFDocument from 'pdfkit';
import * as fs from 'fs';
import * as path from 'path';

export interface ReportData {
  operation: 'encrypt' | 'decrypt';
  targetPath: string;
  affectedFiles: string[];
  timestamp: Date;
}

export function generatePDFReport(data: ReportData): string {
  const timestamp = data.timestamp.toISOString().replace(/[:.]/g, '-').split('T')[0];
  const filename = `fencryptor-report-${timestamp}.pdf`;
  const doc = new PDFDocument({ margin: 50 });

  // Pipe PDF to file
  const outputPath = path.join(process.cwd(), filename);
  doc.pipe(fs.createWriteStream(outputPath));

  // Header
  doc.fontSize(20).text('Fencryptor Operation Report', { align: 'center' });
  doc.moveDown();

  // Details
  doc.fontSize(12);
  doc.text(`Operation: ${data.operation.toUpperCase()}`, { underline: true });
  doc.text(`Target Path: ${data.targetPath}`);
  doc.text(`Timestamp: ${data.timestamp.toLocaleString()}`);
  doc.moveDown();

  // Affected Files
  doc.text('Affected Files:', { underline: true });
  if (data.affectedFiles.length === 0) {
    doc.text('No files processed.');
  } else {
    data.affectedFiles.forEach(file => {
      doc.text(`- ${file}`);
    });
  }

  // Footer
  doc.moveDown(2);
  doc.fontSize(10).text('Generated by @hacker0x1-sh/fencryptor', { align: 'center' });

  doc.end();
  return outputPath;
}